2021-02-04 15:02:06,440 INFO    MainThread:22041 [internal.py:wandb_internal():81] W&B internal server running at pid: 22041
2021-02-04 15:02:06,444 DEBUG   HandlerThread:22041 [handler.py:handle_request():93] handle_request: check_version
2021-02-04 15:02:06,444 DEBUG   SenderThread:22041 [sender.py:send():117] send: header
2021-02-04 15:02:06,444 INFO    WriterThread:22041 [datastore.py:open_for_write():77] open: /notebooks/mltheoryseminar/code/hw0/wandb/run-20210204_150202-12go0vrd/run-12go0vrd.wandb
2021-02-04 15:02:06,444 DEBUG   SenderThread:22041 [sender.py:send():117] send: request
2021-02-04 15:02:06,445 DEBUG   SenderThread:22041 [sender.py:send_request():126] send_request: check_version
2021-02-04 15:02:06,448 DEBUG   Thread-4  :22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): pypi.org:443
2021-02-04 15:02:06,467 DEBUG   Thread-4  :22041 [connectionpool.py:_make_request():461] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 53641
2021-02-04 15:02:06,477 DEBUG   SenderThread:22041 [sender.py:send():117] send: run
2021-02-04 15:02:06,481 DEBUG   SenderThread:22041 [cmd.py:execute():719] Popen(['git', 'cat-file', '--batch-check'], cwd=/notebooks/mltheoryseminar, universal_newlines=False, shell=None, istream=<valid stream>)
2021-02-04 15:02:06,490 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:02:06,628 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2021-02-04 15:02:06,634 INFO    SenderThread:22041 [dir_watcher.py:__init__():165] watching files in: /notebooks/mltheoryseminar/code/hw0/wandb/run-20210204_150202-12go0vrd/files
2021-02-04 15:02:06,634 INFO    SenderThread:22041 [sender.py:_start_run_threads():596] run started: 12go0vrd with start time 1612450925
2021-02-04 15:02:06,635 DEBUG   HandlerThread:22041 [handler.py:handle_request():93] handle_request: run_start
2021-02-04 15:02:06,635 DEBUG   SenderThread:22041 [sender.py:send():117] send: summary
2021-02-04 15:02:06,636 INFO    SenderThread:22041 [sender.py:_save_file():682] saving file wandb-summary.json with policy end
2021-02-04 15:02:06,642 DEBUG   HandlerThread:22041 [meta.py:__init__():34] meta init
2021-02-04 15:02:06,642 DEBUG   HandlerThread:22041 [meta.py:__init__():48] meta init done
2021-02-04 15:02:06,643 DEBUG   HandlerThread:22041 [meta.py:probe():190] probe
2021-02-04 15:02:06,650 DEBUG   HandlerThread:22041 [meta.py:_setup_git():180] setup git
2021-02-04 15:02:06,652 DEBUG   HandlerThread:22041 [cmd.py:execute():719] Popen(['git', 'cat-file', '--batch-check'], cwd=/notebooks/mltheoryseminar, universal_newlines=False, shell=None, istream=<valid stream>)
2021-02-04 15:02:06,658 DEBUG   HandlerThread:22041 [cmd.py:execute():719] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/notebooks/mltheoryseminar, universal_newlines=False, shell=None, istream=None)
2021-02-04 15:02:06,664 DEBUG   HandlerThread:22041 [meta.py:_setup_git():187] setup git done
2021-02-04 15:02:06,665 DEBUG   HandlerThread:22041 [meta.py:_save_pip():52] save pip
2021-02-04 15:02:06,665 DEBUG   HandlerThread:22041 [meta.py:_save_pip():66] save pip done
2021-02-04 15:02:06,665 DEBUG   HandlerThread:22041 [meta.py:probe():231] probe done
2021-02-04 15:02:06,668 DEBUG   SenderThread:22041 [sender.py:send():117] send: files
2021-02-04 15:02:06,669 INFO    SenderThread:22041 [sender.py:_save_file():682] saving file wandb-metadata.json with policy now
2021-02-04 15:02:06,673 DEBUG   Thread-11 :22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:02:06,675 DEBUG   HandlerThread:22041 [handler.py:handle_request():93] handle_request: status
2021-02-04 15:02:06,676 DEBUG   SenderThread:22041 [sender.py:send():117] send: request
2021-02-04 15:02:06,676 DEBUG   SenderThread:22041 [sender.py:send_request():126] send_request: status
2021-02-04 15:02:06,678 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:02:06,785 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2021-02-04 15:02:06,788 DEBUG   SenderThread:22041 [sender.py:send():117] send: run
2021-02-04 15:02:06,793 DEBUG   SenderThread:22041 [cmd.py:execute():719] Popen(['git', 'cat-file', '--batch-check'], cwd=/notebooks/mltheoryseminar, universal_newlines=False, shell=None, istream=<valid stream>)
2021-02-04 15:02:06,804 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:02:06,805 DEBUG   Thread-11 :22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2021-02-04 15:02:06,810 DEBUG   Thread-11 :22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): storage.googleapis.com:443
2021-02-04 15:02:06,936 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2021-02-04 15:02:06,938 INFO    SenderThread:22041 [sender.py:send_run():499] updated run: 12go0vrd
2021-02-04 15:02:07,068 DEBUG   Thread-11 :22041 [connectionpool.py:_make_request():461] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/davidassaraf/CS229br_hw0_memorizing_NN_Underparametrized/12go0vrd/wandb-metadata.json?Expires=1612537326&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=l%2BJh%2BYlAhZTWykNqfzroTroXaHJuyaZHf1ReZq5n5uc9c7mxGZ9SCp4iV9b41SXnGUPVVl12c6w7LW%2F3lZSKJcDuiKztyQ%2BM24sEup6OduzIefKehRYGnRhNLaxQHjeW8h08RhoYm43Pb645MSOoeOuN8NRGyRtsjlobwIIWHYNjZSUnWef%2BSozwokmVeuIyN42BHPyuhtzacmLacTbUyC138T2dxuGDGurefbet73Xub0RAmf4%2F4lVHR8HEzbnLp872Ly6mreQZ1K6tafH2%2BSqepoHkBx3lSOn6G7NHG52IN69IiW4YufmuFKgCkE66MafrJQESb3P6BAFIccAXQA%3D%3D HTTP/1.1" 200 0
2021-02-04 15:02:07,070 INFO    Thread-11 :22041 [upload_job.py:push():133] Uploaded file /tmp/tmpvbthshr9wandb/20rdwbcd-wandb-metadata.json
2021-02-04 15:02:07,636 INFO    Thread-8  :22041 [dir_watcher.py:_on_file_modified():226] file/dir modified: /notebooks/mltheoryseminar/code/hw0/wandb/run-20210204_150202-12go0vrd/files/config.yaml
2021-02-04 15:02:07,636 INFO    Thread-8  :22041 [dir_watcher.py:_on_file_created():213] file/dir created: /notebooks/mltheoryseminar/code/hw0/wandb/run-20210204_150202-12go0vrd/files/wandb-summary.json
2021-02-04 15:02:07,636 INFO    Thread-8  :22041 [dir_watcher.py:_on_file_created():213] file/dir created: /notebooks/mltheoryseminar/code/hw0/wandb/run-20210204_150202-12go0vrd/files/output.log
2021-02-04 15:02:07,637 INFO    Thread-8  :22041 [dir_watcher.py:_on_file_created():213] file/dir created: /notebooks/mltheoryseminar/code/hw0/wandb/run-20210204_150202-12go0vrd/files/requirements.txt
2021-02-04 15:02:07,637 INFO    Thread-8  :22041 [dir_watcher.py:_on_file_created():213] file/dir created: /notebooks/mltheoryseminar/code/hw0/wandb/run-20210204_150202-12go0vrd/files/wandb-metadata.json
2021-02-04 15:02:08,940 DEBUG   Thread-5  :22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:02:09,093 DEBUG   Thread-5  :22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /files/davidassaraf/CS229br_hw0_memorizing_NN_Underparametrized/12go0vrd/file_stream HTTP/1.1" 200 None
2021-02-04 15:02:09,996 DEBUG   SenderThread:22041 [sender.py:send():117] send: stats
2021-02-04 15:02:12,127 DEBUG   Thread-5  :22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /files/davidassaraf/CS229br_hw0_memorizing_NN_Underparametrized/12go0vrd/file_stream HTTP/1.1" 200 None
2021-02-04 15:02:12,617 DEBUG   SenderThread:22041 [sender.py:send():117] send: history
2021-02-04 15:02:12,617 DEBUG   SenderThread:22041 [sender.py:send():117] send: summary
2021-02-04 15:02:12,618 INFO    SenderThread:22041 [sender.py:_save_file():682] saving file wandb-summary.json with policy end
2021-02-04 15:02:12,636 INFO    Thread-8  :22041 [dir_watcher.py:_on_file_modified():226] file/dir modified: /notebooks/mltheoryseminar/code/hw0/wandb/run-20210204_150202-12go0vrd/files/wandb-summary.json
2021-02-04 15:02:12,637 INFO    Thread-8  :22041 [dir_watcher.py:_on_file_modified():226] file/dir modified: /notebooks/mltheoryseminar/code/hw0/wandb/run-20210204_150202-12go0vrd/files/output.log
2021-02-04 15:02:14,433 DEBUG   SenderThread:22041 [sender.py:send():117] send: stats
2021-02-04 15:02:14,506 DEBUG   Thread-5  :22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /files/davidassaraf/CS229br_hw0_memorizing_NN_Underparametrized/12go0vrd/file_stream HTTP/1.1" 404 None
2021-02-04 15:02:18,479 DEBUG   SenderThread:22041 [sender.py:send():117] send: history
2021-02-04 15:02:18,479 DEBUG   SenderThread:22041 [sender.py:send():117] send: summary
2021-02-04 15:02:18,480 INFO    SenderThread:22041 [sender.py:_save_file():682] saving file wandb-summary.json with policy end
2021-02-04 15:02:18,639 INFO    Thread-8  :22041 [dir_watcher.py:_on_file_modified():226] file/dir modified: /notebooks/mltheoryseminar/code/hw0/wandb/run-20210204_150202-12go0vrd/files/wandb-summary.json
2021-02-04 15:02:18,639 INFO    Thread-8  :22041 [dir_watcher.py:_on_file_modified():226] file/dir modified: /notebooks/mltheoryseminar/code/hw0/wandb/run-20210204_150202-12go0vrd/files/output.log
2021-02-04 15:02:18,871 DEBUG   SenderThread:22041 [sender.py:send():117] send: stats
2021-02-04 15:02:21,832 DEBUG   HandlerThread:22041 [handler.py:handle_request():93] handle_request: status
2021-02-04 15:02:21,833 DEBUG   SenderThread:22041 [sender.py:send():117] send: request
2021-02-04 15:02:21,833 DEBUG   SenderThread:22041 [sender.py:send_request():126] send_request: status
2021-02-04 15:02:21,835 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:02:21,941 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2021-02-04 15:02:23,311 DEBUG   SenderThread:22041 [sender.py:send():117] send: stats
2021-02-04 15:02:24,238 DEBUG   SenderThread:22041 [sender.py:send():117] send: history
2021-02-04 15:02:24,238 DEBUG   SenderThread:22041 [sender.py:send():117] send: summary
2021-02-04 15:02:24,239 INFO    SenderThread:22041 [sender.py:_save_file():682] saving file wandb-summary.json with policy end
2021-02-04 15:02:24,641 INFO    Thread-8  :22041 [dir_watcher.py:_on_file_modified():226] file/dir modified: /notebooks/mltheoryseminar/code/hw0/wandb/run-20210204_150202-12go0vrd/files/wandb-summary.json
2021-02-04 15:02:24,642 INFO    Thread-8  :22041 [dir_watcher.py:_on_file_modified():226] file/dir modified: /notebooks/mltheoryseminar/code/hw0/wandb/run-20210204_150202-12go0vrd/files/output.log
2021-02-04 15:02:27,753 DEBUG   SenderThread:22041 [sender.py:send():117] send: stats
2021-02-04 15:02:30,119 WARNING MainThread:22041 [internal.py:wandb_internal():135] Internal process interrupt: 1
2021-02-04 15:02:32,197 DEBUG   SenderThread:22041 [sender.py:send():117] send: stats
2021-02-04 15:02:32,830 DEBUG   HandlerThread:22041 [handler.py:handle_request():93] handle_request: poll_exit
2021-02-04 15:02:32,830 DEBUG   SenderThread:22041 [sender.py:send():117] send: telemetry
2021-02-04 15:02:32,835 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:02:32,963 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 15:02:32,965 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 15:02:32,965 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 15:02:33,645 INFO    Thread-8  :22041 [dir_watcher.py:_on_file_modified():226] file/dir modified: /notebooks/mltheoryseminar/code/hw0/wandb/run-20210204_150202-12go0vrd/files/output.log
2021-02-04 15:02:34,201 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:02:34,322 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 15:02:34,324 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 15:02:34,324 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 15:02:36,633 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:02:36,774 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 15:02:36,775 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 15:02:36,775 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 15:02:36,776 ERROR   SenderThread:22041 [retry.py:__call__():111] Retry attempt failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/internal/internal_api.py", line 129, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/internal/internal_api.py", line 123, in execute
    return self.client.execute(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2021-02-04 15:02:41,311 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:02:41,433 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 15:02:41,434 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 15:02:41,435 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 15:02:49,710 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:02:49,834 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 15:02:49,836 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 15:02:49,836 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 15:03:07,292 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:03:07,605 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 15:03:07,607 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 15:03:07,608 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 15:03:44,260 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:03:44,395 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 15:03:44,397 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 15:03:44,397 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 15:04:52,692 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:04:52,811 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 15:04:52,813 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 15:04:52,813 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 15:06:56,217 WARNING MainThread:22041 [internal.py:wandb_internal():135] Internal process interrupt: 2
2021-02-04 15:06:56,217 ERROR   MainThread:22041 [internal.py:wandb_internal():138] Internal process interrupted.
2021-02-04 15:06:56,434 INFO    WriterThread:22041 [datastore.py:close():258] close: /notebooks/mltheoryseminar/code/hw0/wandb/run-20210204_150202-12go0vrd/run-12go0vrd.wandb
2021-02-04 15:06:56,436 INFO    HandlerThread:22041 [handler.py:finish():312] shutting down handler
2021-02-04 15:07:05,968 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:07:06,339 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 15:07:06,341 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 15:07:06,341 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 15:11:22,562 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:11:22,680 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 15:11:22,682 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 15:11:22,683 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 15:17:20,359 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:17:20,487 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 15:17:20,490 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 15:17:20,490 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 15:23:09,313 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:23:09,439 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 15:23:09,441 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 15:23:09,441 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 15:28:23,988 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:28:24,160 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 15:28:24,163 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 15:28:24,164 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 15:34:34,328 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:34:34,485 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 15:34:34,487 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 15:34:34,488 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 15:39:52,107 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:39:52,238 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 15:39:52,240 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 15:39:52,240 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 15:45:30,982 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:45:31,134 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 15:45:31,136 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 15:45:31,136 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 15:51:23,059 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:51:23,188 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 15:51:23,190 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 15:51:23,190 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 15:56:28,235 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 15:56:28,427 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 15:56:28,428 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 15:56:28,429 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 16:02:27,877 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 16:02:28,006 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 16:02:28,008 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 16:02:28,008 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 16:07:46,889 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 16:07:47,020 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 16:07:47,021 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 16:07:47,022 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 16:12:58,953 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 16:12:59,101 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 16:12:59,102 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 16:12:59,103 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 16:18:58,981 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 16:18:59,112 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 16:18:59,113 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 16:18:59,114 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 16:24:13,385 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 16:24:13,511 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 16:24:13,513 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 16:24:13,513 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 16:29:24,815 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 16:29:24,938 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 16:29:24,939 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 16:29:24,940 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 16:35:35,324 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 16:35:35,453 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 16:35:35,455 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 16:35:35,455 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 16:40:38,988 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 16:40:39,111 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 16:40:39,113 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 16:40:39,113 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 16:46:14,609 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 16:46:14,739 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 16:46:14,741 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 16:46:14,741 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 16:51:45,892 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 16:51:46,011 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 16:51:46,012 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 16:51:46,013 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 16:57:48,783 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 16:57:48,909 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 16:57:48,911 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 16:57:48,911 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 17:02:59,613 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 17:02:59,740 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 17:02:59,742 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 17:02:59,742 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 17:08:00,739 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 17:08:00,867 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 17:08:00,869 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 17:08:00,870 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 17:13:22,347 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 17:13:22,473 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 17:13:22,475 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 17:13:22,476 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 17:18:29,375 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 17:18:29,500 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 17:18:29,502 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 17:18:29,503 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 17:24:31,651 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 17:24:31,779 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 17:24:31,780 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 17:24:31,781 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 17:30:05,026 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 17:30:05,157 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 17:30:05,159 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 17:30:05,159 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 17:36:19,479 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 17:36:19,609 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 17:36:19,611 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 17:36:19,611 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 17:41:53,264 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 17:41:53,408 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 17:41:53,410 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 17:41:53,410 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 17:47:00,346 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 17:47:00,494 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 17:47:00,495 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 17:47:00,496 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 17:52:04,009 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 17:52:04,149 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 17:52:04,151 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 17:52:04,151 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 17:57:40,475 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 17:57:41,256 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 17:57:41,259 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 17:57:41,259 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 18:02:43,604 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 18:02:43,746 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 18:02:43,748 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 18:02:43,748 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 18:08:36,234 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 18:08:36,353 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 18:08:36,355 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 18:08:36,355 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 18:14:50,157 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 18:14:50,283 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 18:14:50,285 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 18:14:50,286 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 18:20:24,964 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 18:20:25,088 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 18:20:25,089 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 18:20:25,090 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 18:26:18,440 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 18:26:18,583 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 18:26:18,584 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 18:26:18,585 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 18:32:17,689 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 18:32:17,833 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 18:32:17,836 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 18:32:17,836 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 18:37:34,561 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 18:37:34,720 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 18:37:34,723 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 18:37:34,723 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 18:43:48,797 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 18:43:48,915 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 18:43:48,916 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 18:43:48,917 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 18:49:16,029 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 18:49:16,174 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 18:49:16,176 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 18:49:16,176 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 18:54:34,373 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 18:54:34,500 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 18:54:34,502 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 18:54:34,502 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 19:00:31,134 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 19:00:31,422 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 19:00:31,424 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 19:00:31,425 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-02-04 19:06:26,531 DEBUG   SenderThread:22041 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-02-04 19:06:26,687 DEBUG   SenderThread:22041 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 409 None
2021-02-04 19:06:26,689 ERROR   SenderThread:22041 [internal_api.py:execute():126] 409 response executing GraphQL.
2021-02-04 19:06:26,689 ERROR   SenderThread:22041 [internal_api.py:execute():127] {"errors":[{"message":"Error 1062: Duplicate entry '210728-12go0vrd' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
